---

- name: (Debian) Update the package list
  apt:
    update_cache: yes

- name: (Debian) Upgrade the system
  apt:
    upgrade: dist
    update_cache: yes

- name: (Debian) Install packages "curl gnupg2 ca-certificates lsb-release debian-archive-keyring"
  apt:
    pkg: 
    - curl
    - gnupg 
    - gnupg2
    - ca-certificates
    - lsb-release
    - debian-archive-keyring
    - apt-transport-https
    state: latest

- name: (Debian) add nginx apt-key
  apt_key: 
    url: https://nginx.org/keys/nginx_signing.key 
    state: present 
    id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    keyring: /usr/share/keyrings/nginx-archive-keyring.gpg

- name: (Debian) add nginx apt repository
  apt_repository: 
    repo: deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] https://nginx.org/packages/debian/ bullseye nginx
    state: present 
    filename: nginx 
    update_cache: yes

- name: (Debian) Install "nginx=1.20.2-1~bullseye"
  apt:
    name: "nginx={{ nginx_version }}-1~bullseye"
    state: present

- name: (Debian) Prevent nginx from being upgraded
  dpkg_selections:
    name: nginx
    selection: hold
  when: freeze_versions|bool == true

- name: (Debian) add bunkerweb key
  apt_key:
    url: https://packagecloud.io/bunkerity/bunkerweb/gpgkey 
    state: present 
    id: 9F5B478F976C7F30191887DCA84F8F37160CA01F
    keyring: /etc/apt/trusted.gpg.d/bunkerity_bunkerweb-archive-keyring.gpg

- name: (Debian) add bukerweb apt repository
  apt_repository: 
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/bunkerity_bunkerweb-archive-keyring.gpg] https://packagecloud.io/bunkerity/bunkerweb/debian bullseye main
    state: present 
    filename: bunkerity_bunkerweb

- name: (Debian) Install "bunkerweb=1.4.1"
  apt:
    name: "bunkerweb={{ bunkerweb_version }}"

- name: (Debian) Prevent bunkerweb from being upgraded
  dpkg_selections:
    name: bunkerweb
    selection: hold
  when: freeze_versions|bool == true

- name: (Debian) Replace /opt/bunkerweb/variables.env
  copy:
    src: "{{ variables_env }}"
    dest: /opt/bunkerweb/variables.env
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: (Handler) restart bunkerweb

- name: (Debian) If var {{enable_ui}} is false, systemctl disable bunkerweb-ui
  service:
    name: bunkerweb-ui
    state: stopped
    enabled: no
  when: enable_ui|bool == false
